ACTIVE_RIDE_STATUSES = [
    "REQUESTED",
    "ACCEPTED",
    "DRIVER_ARRIVING",
    "STARTED",
]

COMPLETED_RIDE_STATUS = "COMPLETED"
CANCELLED_RIDE_STATUS = "CANCELLED"

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100


# ============================================================
# API ERROR CODES
# ============================================================

AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR"
DRIVER_PROFILE_NOT_FOUND = "DRIVER_PROFILE_NOT_FOUND"
RIDE_NOT_FOUND = "RIDE_NOT_FOUND"
INVALID_RIDE_STATUS = "INVALID_RIDE_STATUS"
INVALID_REQUEST = "INVALID_REQUEST"
INVALID_FARE_DATA = "INVALID_FARE_DATA"
INVALID_LOCATION = "INVALID_LOCATION"
INVALID_COORDINATES = "INVALID_COORDINATES"
DRIVER_NOT_ASSIGNED = "DRIVER_NOT_ASSIGNED"
NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
DRIVER_ONLY = "DRIVER_ONLY"