# Generated by Django 5.2.17 on 2026-08-12 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_ride_ride_type_alter_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='business.vehicletype'),
        ),
    ]
