# Generated by Django 5.2.17 on 2026-08-19 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_ride_ride_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'driver_locations',
            },
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_available',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='availability_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy')], db_index=True, default='OFFLINE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', 'status'], name='ride_passenger_status_idx'),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='business.driverprofile'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='driver_loca_latitud_c634eb_idx'),
        ),
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['driver'], name='driver_loca_driver__da2ef0_idx'),
        ),
    ]
