# Generated by Django 5.2.17 on 2026-08-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_driverlocation_remove_driverprofile_is_available_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='driverlocation',
            new_name='driver_loc_coords_idx',
            old_name='driver_loca_latitud_c634eb_idx',
        ),
        migrations.RenameIndex(
            model_name='driverlocation',
            new_name='driver_loc_driver_idx',
            old_name='driver_loca_driver__da2ef0_idx',
        ),
    ]
