# Generated by Django 5.2.17 on 2026-08-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_notification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'ride', 'notification_type'), name='unique_user_ride_notification'),
        ),
    ]
