# Generated by Django 5.2.17 on 2026-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_notification_unique_user_ride_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_user_ride_notification',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_a4dd5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_7336fd_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_19df93_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
    ]
