# Generated by Django 5.2.17 on 2026-08-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('RIDE_REQUEST', 'Ride Request'), ('RIDE_ACCEPTED', 'Ride Accepted'), ('DRIVER_ARRIVING', 'Driver Arriving'), ('RIDE_STARTED', 'Ride Started'), ('RIDE_COMPLETED', 'Ride Completed'), ('RIDE_CANCELLED', 'Ride Cancelled'), ('DRIVER_LOCATION', 'Driver Location'), ('SYSTEM', 'System')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='business_no_user_id_2c603f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='business_no_user_id_5c6d39_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='business_no_notific_5f52aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'ride', 'notification_type'), name='unique_user_ride_notification'),
        ),
    ]
