# Generated by Django 5.2.17 on 2026-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ride',
            name='ride_passenger_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ride',
            new_name='ride_passenger_idx',
            old_name='rides_passeng_2390e2_idx',
        ),
        migrations.RenameIndex(
            model_name='ride',
            new_name='ride_driver_idx',
            old_name='rides_driver__8fdcf2_idx',
        ),
        migrations.RenameIndex(
            model_name='ride',
            new_name='ride_vehicle_idx',
            old_name='rides_vehicle_b66180_idx',
        ),
        migrations.RenameIndex(
            model_name='ride',
            new_name='ride_status_idx',
            old_name='rides_status_376a74_idx',
        ),
        migrations.RenameIndex(
            model_name='ride',
            new_name='ride_requested_at_idx',
            old_name='rides_request_bff1c1_idx',
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['updated_at'], name='ride_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', 'status', '-requested_at'], name='ride_pass_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status', '-requested_at'], name='ride_driver_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', '-requested_at'], name='ride_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', '-requested_at'], name='ride_passenger_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', '-requested_at'], name='ride_driver_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['fare'], name='ride_fare_idx'),
        ),
    ]
